// This file was generated by json2swift. https://github.com/ijoshsmith/json2swift

import Foundation

struct User: CreatableFromJSON {
    let botId: BotId
    let email: String
    let isActive: Bool
    let name: String
    let restaurantRecordId: Int
    let userId: Int
    let userName: String
    let userToken: String
    let restaurant_color_code: String
    init(botId: BotId, email: String, isActive: Bool, name: String, restaurantRecordId: Int, userId: Int, userName: String, userToken: String,restaurant_color_code:String) {
        self.botId = botId
        self.email = email
        self.isActive = isActive
        self.name = name
        self.restaurantRecordId = restaurantRecordId
        self.userId = userId
        self.userName = userName
        self.userToken = userToken
        self.restaurant_color_code = restaurant_color_code
    }
    init?(json: [String: Any]) {
        guard let botId = BotId(json: json, key: "bot_id") else { return nil }
        guard let email = json["email"] as? String else { return nil }
        guard let isActive = json["is_active"] as? Bool else { return nil }
        guard let name = json["name"] as? String else { return nil }
        guard let restaurantRecordId = json["restaurant_record_id"] as? Int else { return nil }
        guard let userId = json["user_id"] as? Int else { return nil }
        guard let userName = json["user_name"] as? String else { return nil }
        guard let userToken = json["user_token"] as? String else { return nil }
        guard let restaurant_color_code = json["restaurant_color_code"] as? String else { return nil }
        self.init(botId: botId, email: email, isActive: isActive, name: name, restaurantRecordId: restaurantRecordId, userId: userId, userName: userName, userToken: userToken,restaurant_color_code:restaurant_color_code)
    }
    struct BotId: CreatableFromJSON {
        let tWITTER: String
        let wEBCHAT: String
        let WHATSAPP: String
        init(tWITTER: String, wEBCHAT: String, WHATSAPP: String) {
            self.tWITTER = tWITTER
            self.wEBCHAT = wEBCHAT
            self.WHATSAPP = WHATSAPP
        }
        init?(json: [String: Any]) {
             let tWITTER = json["TWITTER"] as? String ?? ""
             let wEBCHAT = json["WEBCHAT"] as? String ?? ""
             let WHATSAPP = json["WHATSAPP"] as? String ?? ""
            self.init(tWITTER: tWITTER, wEBCHAT: wEBCHAT, WHATSAPP: WHATSAPP)
        }
    }
}
